HRiVote/Models/OpenPosition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HRiVote.Models
{
    public class OpenPosition
    {
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [ScaffoldColumn(false)]
        public bool Status { get; set; }
        [DataType(DataType.Date), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Required]
        public DateTime StartOfJobOpenning { get; set; }
        [DataType(DataType.Date), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [Required]
        public DateTime EndOfJobOpenning { get; set; }
        public OpenPosition()
        {

        }
        public void Update(OpenPosition old,OpenPosition newpos)
        {
            old.Description = newpos.Description;
            old.EndOfJobOpenning = newpos.EndOfJobOpenning;
            old.Name = newpos.Name;
            old.StartOfJobOpenning = newpos.StartOfJobOpenning;
        }
    }
}

HRiVote/Controllers/OpenJobPossitionsController.cs
using HRiVote.DAL;
using HRiVote.Models;
using HRiVote.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRiVote.Controllers
{
    public class OpenJobPossitionsController : Controller
    {
        private Entity db = new Entity();
        // GET: OpenJobPossitions
        public ActionResult Index(bool? status, int? id, int? Editid)
        {
            List<OpenPosition> open = new List<OpenPosition>();
            if (status.HasValue)
            {
                open = db.pozicii.Where(x => x.Status == status).ToList();

            }
            else
            {
                open = db.pozicii.ToList();
            }
            var ViewModel = new OpenJobViewModel
            {
                opens = open,
            };
            List<int> ids = db.pozicii.Select(x => x.ID).ToList();
            if (id.HasValue)
            {
                if (ids.Contains(id.Value))
                {
                    ViewModel.open = ViewModel.opens.Single(x => x.ID == id); 
                }
            }
            if (Editid.HasValue)
            {
                ViewModel.Edit = ViewModel.opens.Where(x => x.ID == Editid).ToList();
            }

            return View(ViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult IndexPost(OpenPosition item)
        {
            var possitions = db.positions.ToList();
            var job = db.pozicii.Single(x => x.ID == item.ID);
            if(job == null)
            {
                return HttpNotFound();
            }
            else
            {
                //UPdatte na oglasot i dokolku taa pozicija ja nema vo bazata na rabotni pozicii se dodava
                job.Update(job, item);               
                job.Status = true;
                if (!possitions.Select(x => x.Title).Contains(item.Name))
                {
                    AddtoPossitions(item);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        public ActionResult OpenPosition()
        {
            Models.OpenPosition open = new Models.OpenPosition();
            return View(open);

        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(OpenPosition open)
        {
            var possitions = db.positions.ToList();
            if (open.ID == 0)
            {

                if (ModelState.IsValid)
                {
                    open.Status = true;
                    db.pozicii.Add(open);
                    if (!possitions.Select(x => x.Title).Contains(open.Name))
                    {
                        AddtoPossitions(open);
                    }
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "We couldn't validate your input please try again");
                    return View("OpenPosition", open);
                }
            }
            else
            {
                var pos = db.pozicii.Single(x => x.ID == open.ID);                
                if (!possitions.Select(x => x.Title).Contains(open.Name))
                {
                    AddtoPossitions(open);                   
                }
                pos.Update(open, pos);
                pos.Status = true;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        //Metod za Dodavanje na pozicii vo clasata na pozicii
            public void AddtoPossitions(OpenPosition open)
            {
            var possition = new JobPosition()
            {
                Status = true,
                Title = open.Name
            };
            db.positions.Add(possition);
            }
    }
}

HRiVote/Views/OpenJobPossitions/Details.cshtml
@model HRiVote.Models.OpenPosition
<div class="container Back col-sm-offset-1",style="border: solid transparent;border-radius: 20px;">
    <div>
        <h4>OpenPosition</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.StartOfJobOpenning)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.StartOfJobOpenning)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EndOfJobOpenning)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EndOfJobOpenning)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "UpdatePossition", new { id = Model.ID }, new { @class = "btn btn-primary fa fa-pencil", @style = "border-radius: 12px;padding: 6px 20px;font-size: 15px;" }) |
        @Html.ActionLink("Back to List", "Index", "", new { @class = "btn btn-primary fa fa-backward", @style = "border-radius: 12px;padding: 6px 20px;font-size: 15px;" })
    </p>
</div>

HRiVote/Views/OpenJobPossitions/Index.cshtml
@model HRiVote.ViewModels.OpenJobViewModel

<div class="container Back col-sm-offset-1" style="border: solid transparent;border-radius: 20px;">
    <br />
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css">
    <p>
        @Html.ActionLink(" CreateNew", "OpenPosition","",new { @class = "btn btn-primary glyphicon glyphicon-pencil", @style = "border-radius: 12px;padding: 6px 20px;font-size: 15px;" })
    </p>
    <div class="form-group">
        <table id="mytable" class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Start of Job Oppenning
                    </th>
                    <th>
                        End of Job Oppenning
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.opens)
                {
                    if (Model.Edit != null)
                    {
                            foreach (var tag in Model.Edit)
                            {
                                <tr>
                                    @if (item.ID == tag.ID)
                                    {
                                        using (Html.BeginForm("IndexPost", "OpenJobPossitions", FormMethod.Post))
                                        {
                                            @Html.AntiForgeryToken()
                                            @Html.HiddenFor(x => item.ID)
                                            <td>@Html.EditorFor(x => item.Name)</td>
                                            <td>@Html.EditorFor(x => item.Description)</td>
                                            <td>@Html.EditorFor(x => item.StartOfJobOpenning)</td>
                                            <td>@Html.EditorFor(x => item.EndOfJobOpenning)</td>
                                            <td>
                                                <input type="submit" value="Update" class="btn btn-success glyphicon glyphicon-pencil" />
                                                @Html.ActionLink(" Return", "Index", null, new { @class = "btn btn-primary fa fa-backward" })
                                            </td>
                                        }
                                    }
                                    else
                                    {
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Description)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.StartOfJobOpenning)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.EndOfJobOpenning)
                                        </td>
                                        <td>
                                            @Html.ActionLink(" Details", "Index", new { id = item.ID }, new { @class = "btn btn-info glyphicon glyphicon-info-sign" }) |
                                            @Html.ActionLink(" Edit", "Index", new { Editid = item.ID }, new { @class = "btn btn-primary glyphicon glyphicon-pencil" }) |
                                            @if (item.Status == true)
                                            {
                                                <button class="btn btn-danger glyphicon glyphicon-trash js-delete" data-project-id="@item.ID" type="button"> Delete</button>
                                            }
                                            else
                                            {
                                                <button class="btn btn-primary glyphicon glyphicon-arrow-up js-update" data-project-id="@item.ID" type="button"> Add</button>
                                            } 
                                         </td>
                                    }
                                  </tr>
                            }
                        }
                    
                    else
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartOfJobOpenning)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EndOfJobOpenning)
                        </td>
                        <td>
                            @Html.ActionLink(" Details", "Index", new { id = item.ID }, new { @class = "btn btn-info glyphicon glyphicon-info-sign" }) |
                            @Html.ActionLink(" Edit", "Index", new { Editid = item.ID }, new { @class = "btn btn-primary glyphicon glyphicon-pencil" }) |
                            @if (item.Status == true)
                            {
                                <button class="btn btn-danger glyphicon glyphicon-trash js-delete"  data-project-id="@item.ID" type="button"> Delete</button>
                            }
                            else
                            {
                                <button class="btn btn-primary glyphicon glyphicon-arrow-up js-update" data-project-id="@item.ID"  type="button"> Add</button>
                            }
                        </td>
                    </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
@if (Model.open != null)
{
    @Html.HiddenFor(x => x.open.ID, new { @id = "id" })
    <div class="container col-sm-offset-1">
        <div id="modal" class="modal" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header" style="border:solid 1px black;">
                        <h2>Details</h2>
                        <h4>OpenPosition</h4>
                    </div>
                    <div class="modal-body" style="font-size:15px !important;">
                        @Html.Partial("_PartialOpenView", Model.open)
                    </div>
                </div>
            </div>
        </div>
    </div>
}
@section scripts{
  <script>
      $(document).ready(function () {
          $("#mytable").DataTable();
          var id = document.getElementById("id")
          if (id != null) {
              $("#modal").show();
          }
          $("#mytable").on("click", ".js-delete", function () {
              var button = $(this);
              var dialog = bootbox.dialog({
                  title: 'Remove',
                  message: "<p>Are you sure you want to remove it</p>",
                  buttons: {
                      no: {
                          label: "Cancel",
                          className: 'btn1 btn-default',
                          callback: function () {
                              dialog.modal('hide')
                          }
                      },
                      ok: {
                          label: "Yes",
                          className: 'btn1 btn-danger',
                          callback: function () {
                              $.ajax({
                                  url: "/api/Open/" + button.attr("data-project-id"),
                                  method: "DELETE",
                                  success: function () {

                                      button.parents("tr").remove();
                                  }
                              })

                          }
                      }
                  }
              });
          });
          $("#mytable").on("click", ".js-update", function () {
              var self = $(this);
              var dialog = bootbox.dialog({
                  title: 'Remove',
                  message: "<p>Are you sure you want to remove it</p>",
                  buttons: {
                      no: {
                          label: "no",
                          className: 'btn1 btn-danger',
                          callback: function () {
                              dialog.modal('hide')
                          }
                      },
                      ok: {
                          label: "ok",
                          className: 'btn1 btn-default',
                          callback: function () {
                              $.ajax({
                                  url: "/api/Open/" + button.attr("data-project-id"),
                                  method: "Put",
                                  success: function () {

                                      self.parents("tr").remove();
                                  }
                              })

                          }
                      }
                  }
              });
          });
      });
    </script>
    }

HRiVote/Views/OpenJobPossitions/OpenPosition.cshtml
@model HRiVote.Models.OpenPosition
<div class="container Back col-sm-offset-1" style="border: solid transparent;border-radius: 20px;">
    @using (Html.BeginForm("Save","OpenJobPossitions",FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>OpenPosition</h4>
            @Html.HiddenFor(x=>x.ID)
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            @if (Model.ID>0)
            {
                <div >
                    @Html.Label("Previous Date of Job Openning", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBox("date",Model.StartOfJobOpenning ,  new { @class = "form-control",@readonly=true })
                        @Html.ValidationMessageFor(model => model.StartOfJobOpenning, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br /><br /><br />
                <div class="form-group">
                    @Html.LabelFor(model => model.StartOfJobOpenning, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartOfJobOpenning, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StartOfJobOpenning, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div>
                    @Html.Label("Previous Date of Job Clossing", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBox("date1", Model.EndOfJobOpenning, new { @class = "form-control", @readonly = true })
                        @Html.ValidationMessageFor(model => model.StartOfJobOpenning, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br /><br /><br />
                <div class="form-group">
                    @Html.LabelFor(model => model.EndOfJobOpenning, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EndOfJobOpenning, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EndOfJobOpenning, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
            else
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.StartOfJobOpenning, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.StartOfJobOpenning, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StartOfJobOpenning, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.EndOfJobOpenning, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EndOfJobOpenning, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EndOfJobOpenning, "", new { @class = "text-danger" })
                    </div>
                </div>

            }






            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink(" Back to List", "Index","",new { @class = "btn btn-primary fa fa-backward"})
    </div>
</div>