HRiVote/Models/Calendar.cs
using HRiVote.Validations;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HRiVote.Models
{
    public class Calendar
    {
       
        public int Id { get; set; }
        
        public int? EmployeeID { get; set; }
        
        public Employee employee { get; set; }            
        [ScaffoldColumn(false)]
        
        public string Title { get; set; }
        [ScaffoldColumn(false)]
        public string Color { get;private set; }
       
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [CalendarStart]
        [Required]
        public DateTime? StartOfVacation { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [CalendarEnd]
        [Required]
        public DateTime? EndOfVacation { get; set; }
        [ScaffoldColumn(false)]
        public string Description { get;private set; }
        [ScaffoldColumn(false)]
        public bool status { get; private set; }
        public string EmpName { get; private set; }
        public Calendar()
        {

        }
        public void description(Employee employee)
        {

            if (Title == "Sick")
            {
               Color = "#bd180e";
            }
            if (Title == "Vacation")
            {
                Color = "#23a127";
            }
            if (Title == "Official Leave")
            {
                Color = "#345578";
            }

            EmpName = employee.FullName;
            if (EndOfVacation.HasValue)
            {
                Description = employee.FullName + " is on " + Title + " till : " + EndOfVacation.Value.ToShortDateString();
            }
            status = true;
        }
        public void Update(Calendar oldCalendar,Calendar NewCalendar)
        {
            NewCalendar.Title = oldCalendar.Title;
            NewCalendar.StartOfVacation = oldCalendar.StartOfVacation;
            NewCalendar.EmployeeID = oldCalendar.EmployeeID;
            NewCalendar.EndOfVacation = oldCalendar.EndOfVacation;
        }
        public void Remove()
        {
            status = false;
        }
    }
}

HRiVote/ViewModels/CalendarViewModel.cs
using HRiVote.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HRiVote.ViewModels
{
    public class CalendarViewModel
    {
        public Calendar Calendar { get; set; }
        public IEnumerable<Employee> Employes { get; set; }
    }
}

HRiVote/Controllers/API/CalendarController.cs
using HRiVote.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace HRiVote.Controllers.API
{
    public class CalendarController : ApiController
    {
        private Entity db;
        public CalendarController()
        {
            db = new Entity();
        }
        [HttpDelete]
        public void Remove(int id)
        {
            var cal = db.kalendar.Single(x => x.Id == id);
            if (cal == null)
            {
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            }
            else
            {
                var emp = db.emps.Single(x => x.ID == cal.EmployeeID);
                cal.Remove();
               // emp.IsAvailable = true;
                db.SaveChanges();
                //db.kalendar.Remove()
            }
        }
    }
}

HRiVote/Controllers/CalendarController.cs
using HRiVote.DAL;
using HRiVote.Models;
using HRiVote.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.IO;

namespace HRiVote.Controllers
{
    public class CalendarController : Controller
    {
        Entity db;
        public CalendarController()
        {
            db = new Entity();
        }
        // GET: Calendar
        public ActionResult OnLeaveDays( string title)
        {
            if (!string.IsNullOrWhiteSpace(title))
            {
                TempData["title"] = title;
            }
            var viewmodel = new CalendarViewModel
            {
                Calendar = new Calendar(),
                Employes = db.emps.Where(x=>x.IsAvailable==true).ToList()
            };
            return View(viewmodel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Open(Calendar calendar, HttpPostedFileBase file)
        {
            
            var viewmodel = new CalendarViewModel()
            {
                Calendar = new Calendar(),
                Employes = db.emps.Where(x=>x.IsAvailable==true).ToList()
            };
            if (calendar.Id == 0)
            {
                if (calendar.EmployeeID != null || calendar.EmployeeID > 0)
                {
                    var employee = db.emps.Single(x => x.ID == calendar.EmployeeID);
                    if (TempData["title"] != null)
                    {
                        var title = TempData["title"].ToString();
                        TempData.Keep("title");
                        calendar.Title = title;
                        Upload(file, employee, calendar);
                        calendar.description(employee);
                        if (ModelState.IsValid)
                        {
                            db.kalendar.Add(calendar);
                            db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            return View("OnLeaveDays", viewmodel);
                        }
                    }
                    else
                    {
                        return View("OnLeaveDays", viewmodel);
                    }

                }


                else
                {
                    ModelState.AddModelError("", "You Must Select an Employee ");
                    return View("OnLeaveDays", viewmodel);
                }


            }

            else
            {
                if (ModelState.IsValid)
                {
                    if (calendar.EmployeeID != null)
                    {
                        var kalendar = db.kalendar.Single(x => x.Id == calendar.Id);
                        var employee = db.emps.Single(x => x.ID == calendar.EmployeeID);
                        kalendar.Update(calendar, kalendar);
                        kalendar.description(employee);
                        Upload(file, employee, calendar);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        viewmodel.Calendar = calendar;
                        ModelState.AddModelError("", "The Input Couldn't be validated try again");
                        return View("OnLeaveDays", viewmodel);
                    }
                }
                else
                {
                    viewmodel.Calendar = calendar;
                    ModelState.AddModelError("", "The Input Couldn't be validated try again");
                    return View("OnLeaveDays", viewmodel);
                }
            }
        }
        public ActionResult Edit(int id)
        {
            var kalenadr = db.kalendar.Include(c=>c.employee).Single(x => x.Id == id);
            var emps = db.emps.Where(x => x.IsAvailable == true).ToList();
            
            var viewmodel = new CalendarViewModel()
            {
                Calendar = kalenadr,
                Employes = emps
            };
            return View("OnLeaveDays", viewmodel);
        }
        public ActionResult Index()
        {
            var viewmodel = new CalendarViewModel
            {
                Calendar = new Calendar(),
                Employes = db.emps.Where(x => x.IsAvailable == true).ToList()
            };
            return View(viewmodel);
        }
        public JsonResult GetData()
        {
            var kalen = db.kalendar.Where(x => x.status == true).ToList();
            return new JsonResult { Data = kalen, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

   
        public void Upload(HttpPostedFileBase file,Employee employee,Calendar calendar)
        {
            if (file != null && file.ContentLength > 0)
            {
                var name = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Managment/Document's"), name);
                file.SaveAs(path);
                EmployeeFiles files = new EmployeeFiles()
                {
                    EmployeeID = employee.ID,
                    File = "~/Managment/Document's/" + file.FileName,
                    Type = calendar.Title
                };
                db.empf.Add(files);
                db.SaveChanges();
            }
        }
  
      

    }
}

HRiVote/Views/Calendar/Index.cshtml
<link href="~/Content/fullcalendar.min.css" rel="stylesheet" />
<link href="~/Content/fullcalendar.print.css" rel="stylesheet" media="print" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />

@model HRiVote.ViewModels.CalendarViewModel
    @*<h1 class="text-center marg"style="font-weight:500;">Calendar</h1>*@
<div id="calendar" class="col-sm-10 col-sm-offset-2 "style="border:solid 1px black;">
    <div id="modal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" style="border:solid 1px black;">
                    <button type="button"class="close"data-dismiss="modal">&times;</button>
                    <h4 class="modal-title"><span id="eventTitle"></span></h4>
                </div>
                <div class="modal-body" style="font-size:15px !important;">
                    <p id="pDetails"></p>
                    <div>
                    <button id="btnDelete" class="btn btn-danger btn-sm pull-right">
                        <span class="glyphicon glyphicon-remove"></span> Remove
                    </button>
                    <button id="btnEdit" class="btn btn-primary btn-sm pull-right" style="margin-right:5px;">
                        <span class="glyphicon glyphicon-pencil"></span> Edit
                    </button>
                    </div>                                 
                </div>
                <div class="modal-footer" style="border:solid 1px black;">
                    
                    <button type="button"class="btn btn-default"data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{

<script src="~/Scripts/moment-with-locales.min.js"></script>
<script src="~/Scripts/fullcalendar.js"></script>
<script src="~/Scripts/lib/jquery-ui.min.js"></script>
<script src="~/Scripts/fullcalendar.min.js"></script>
<script src="~/Scripts/moment.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var events = [];
            var selected = null;
            var ID;
            FetchEventAndRenderCalendar();
            function FetchEventAndRenderCalendar() {
                $.ajax({
                    type: "GET",
                    url: "/Calendar/GetData",
                    success: function (data) {
                        $.each(data, function (i, v) {
                            ID = v.Id;
                            $id = v.Id;
                            events.push({
                                empid:v.EmployeeID,
                                eventId: v.Id,
                                title: v.EmpName,
                                start: moment(v.StartOfVacation),
                                end:v.EndOfVacation!=null ? moment(v.EndOfVacation):null,
                                description: v.Description,
                                color: v.Color
                            });
                        })
                        GenerateCalendar(events);
                    },
                    error: function (error) {
                        alert("Failed");
                    }
                })
            }
            function GenerateCalendar(events) {
                $('#calendar').fullCalendar('destroy');
                $('#calendar').fullCalendar({
                    contentHeight: 600,
                    default: "30%",
                    defaultDate: new Date(),
                    timeFormat: 'H(:mm)',
                    header: {
                        left: '',
                        center: 'prev , next today',
                        right:""
                    },
                    eventLimit: true,
                    events: events,
                    eventClick: function (calEvent, jsEvent, view) {
                        selected = calEvent;
                        $("#modal #eventTitle").text(calEvent.title)
                        var $description = $('<div/>');
                        $description.append($("<p/>").html('<b> Start :</b>' + calEvent.start.format(" DD-MMM-YYYY")));                       
                        $description.append($("<p/>").html('<b> Description : </b>' + calEvent.description));
                        $("#modal pDetails").empty().html($description);
                        $('#pDetails').html($description);
                        $("#btn").val($id);
                        $("#modal").modal();
                    },     
                })
            }
            $('#btnEdit').click(function get() {               
                location.href = '@Url.Action("Edit", "Calendar")?id='+ID
            });
            
            $('#btnDelete').click(function () {
                if (selected != null) {
                    var dialog = bootbox.dialog({
                        title: 'Remove',
                        message: "<p>Are you sure you want to remove it</p>",
                        buttons: {
                            no: {
                                label: "Cancel",
                                className: 'btn1 btn-default',
                                callback: function () {
                                    dialog.modal('hide')
                                }
                            },
                            ok: {
                                label: "Yes",
                                className: 'btn1 btn-danger',
                                callback: function () {
                                    $.ajax({
                                        type: "Delete",
                                        url: '@Url.Action("Calendar","api")?id=' + ID,
                                        // data: { 'id': selected.eventId },
                                        success: function () {
                                            $('#modal').modal('hide');
                                            location.href = '@Url.Action("Index","Calendar")';
                                        },
                                        error: function () {
                                            alert('Failed');
                                        }
                                    })

                                }
                            }
                        }
                    });
                   
                 }
            })
        })
    </script>

 }

HRiVote/Views/Calendar/OnLeaveDays.cshtml
@model HRiVote.ViewModels.CalendarViewModel
<div class="container Back col-sm-offset-1" style="border: solid transparent;border-radius: 20px;">
    @using (Html.BeginForm("Open","Calendar",FormMethod.Post,new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Calendar</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
          
            
            <div class="form-group">
                @Html.LabelFor(model => model.Calendar.EmployeeID, "Employee", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.Calendar.EmployeeID, new SelectList(Model.Employes, "ID", "FullName",Model.Calendar.Id), "---Select an Employee---", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Calendar.EmployeeID, "", new { @class = "text-danger" })
                </div>
            </div>
            
            @if (Model.Calendar.Id > 0)
            {
                <div class="form-group">
                    @Html.LabelFor(x => x.Calendar.Title,new { @class="control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.DropDownListFor(x => x.Calendar.Title, new List<SelectListItem>()
                   {
                       new SelectListItem() {Text="Sick Leave",Value="Sick Leave" },
                       new SelectListItem() {Text="Vacation",Value="Vacation" },
                       new SelectListItem() {Text="Official leave",Value="Official leave" } },
                       "--- Select---",new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Calendar.Title, "",new { @class="text-danger"})
                    </div>
                </div>
            }
            <div class="form-group">
                @Html.LabelFor(model => model.Calendar.StartOfVacation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Calendar.StartOfVacation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Calendar.StartOfVacation, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Calendar.EndOfVacation, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Calendar.EndOfVacation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Calendar.EndOfVacation, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("File Upload", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <i class="fa fa-cloud-upload"></i>
                    <input type="file" class="btn " id="file" name="file" value="Search" />
                </div>
            </div>
                @Html.HiddenFor(x=>x.Calendar.Id)
                @Html.HiddenFor(x=>x.Calendar.EmployeeID)
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>

    <br />
    <div class="container Back col-sm-offset-1" >
   
        @Html.ActionLink("Back to List", "Index","",new { @class = "btn btn-primary fa fa-backward"})
    
</div>