HRiVote/Controllers/API/TreeController.cs
using HRiVote.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace HRiVote.Controllers.API
{

    public class TreeController : ApiController
    {
        public Entity db;
        public TreeController()
        {
            db = new Entity();
        }
     
    }
}

HRiVote/Controllers/TreeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

using System.Data;
using System.Net;
using HRiVote.Filters;
using HRiVote.DAL;
using HRiVote.Models;
using System.IO;
using HRiVote.ViewModels;

namespace DojoTree.Controllers
{
    public class TreeController : Controller
    {
        private Entity db = new Entity();

        // GET     /Tree/Data/3
        public ActionResult Index(string name)
        {
            var notify = new Nottifications();
            var Kalendar = db.kalendar.Include(c=>c.employee).ToList();
            var Candidates = db.aplikanti.ToList();
            var openposs = db.pozicii.ToList();
            foreach(var item in Kalendar)
            {
                if (item.status == true && item.EndOfVacation.Value.Date <= DateTime.Now.Date)
                {
                    notify.Notifications.Add("The " + item.EmpName + " " + item.Title + " has Ended/Ending today please update his/hers status");
                }
            }
            foreach(var item in Candidates)
            {
                if (item.InterviewDate.Date == DateTime.Now.Date)
                {
                    notify.Notifications.Add("The Candidate " + item.FirstName + " " + item.LastName + " has Interview today");
                }
                if (item.InterviewDate.Date < DateTime.Now.Date)
                {
                    notify.Notifications.Add("The Candidate " + item.FirstName + " " + item.LastName + " Interview Passed please update the Status");
                }
            }
            foreach(var item in openposs)
            {
                if(item.Status==true && item.EndOfJobOpenning.Date <= DateTime.Now.Date)
                {
                    notify.Notifications.Add("The job Oppening : " + item.Name + " is ending today/has ended please update the status");
                }
            }

            string path = Server.MapPath("~/Managment/");
            List<string> picFolders = new List<string>();

           // if (Directory.GetFiles(path, "*").Length > 0)
                picFolders.Add(path);

            foreach (string dir in Directory.GetDirectories(path, "*", SearchOption.AllDirectories))
            {
                //if (Directory.GetFiles(dir, "*").Length > 0)
                    picFolders.Add(dir);
            }
            picFolders.RemoveAt(0);
            var viewmodel = new FileViewModel()
            {
                pics = picFolders,
                files = "~/Managment/" + name,
                name=name
            };
           
            return View(viewmodel);
        }
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file ,string files)
        {

            if (file != null && file.ContentLength > 0)
            {
                var name = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath(files), name);
                file.SaveAs(path);
                return RedirectToAction("Index");

            }
            else
            {
                ViewBag.Error = "You must select a file for download";
                return RedirectToAction("Index");
            }
           
        }
        public ActionResult Delete(string path)
        {
            if (System.IO.File.Exists(path))
            {
                var emps = db.emps.ToList();
                var candidate = db.aplikanti.ToList();
              foreach(var item in emps)
                {
                    if (item.CV.Contains(path))
                    {
                        item.CV = "No CV uploaded";
                    }
                    if (item.Photo.Contains(path))
                    {
                        item.Photo = "No photo uploaded";
                    }
                }
              foreach(var item in candidate)
                {
                    if (item.CV.Contains(path))
                    {
                        item.CV = "Cv not Uploaded";
                    }
                }
                db.SaveChanges();
                System.IO.File.Delete(path);
            }
            return RedirectToAction("Index");
        }
    }
}

HRiVote/Views/Tree/Index.cshtml
@model HRiVote.ViewModels.FileViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Upload", "Tree", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="container col-sm-offset-1">
        <h2 class="text-center">File Viewer</h2>
        <br /><br /><br />
    <div class="row">
        <div class="col-sm-1">
            <span class="glyphicon glyphicon-upload"></span> 
       
            <input type="file" name="file" />
        </div>
        <div class="col-sm-2 col-sm-offset-1" style="margin-top: 7px;">
            <p class="text-danger">@ViewBag.Error</p>
            @Html.HiddenFor(x => x.files)
            <input type="submit" value="upload" class="btn btn-primary" />
        </div>
    </div>
        <br /><br />
    <div class="row">
     @foreach (var item in Model.pics)
     {
         var file = item.Substring(32);


            <div class="col-md-2 col-md-offset-1">
               @if (Model.name == file)
               {
                @Html.ActionLink(" " + file, "Index", new { name = file }, new { @class = "js-click glyphicon glyphicon-folder-open", @style = "font-size:20px;color:darkorange" })
               }
               else
               {
              @Html.ActionLink(" " + file, "Index", new { name = file }, new {@class = "js-click glyphicon glyphicon-folder-close", @style = "font-size:20px;color:darkorange" })
               }
            </div>
     }
    
    </div>
    <br /><br />
    <div class="row col-md-12">
     
        @foreach (var imgPath in Directory.GetFiles(Server.MapPath(Model.files)))
        {

            var img = new FileInfo(imgPath);
            <div class="col-md-3 button-top">
                <a href="@Url.Content(String.Format(Model.files + "/{0}", img.Name))" target="_blank"><img src="@Url.Content(String.Format(Model.files + "/{0}", img.Name))" alt="@imgPath" width="200" /></a>
                <div>
                    <div class="col-md-2 button-down">
                        @Html.ActionLink(" Delete", "Delete", new { path = imgPath }, new { @class = "btn btn-danger glyphicon glyphicon-trash" })
                    </div>
                </div>
            </div>
        }
    </div>
    
    @Html.HiddenFor(x => x.name,new { @id="file"})
</div>
}
@section scripts{
<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script src="~/Scripts/jquery-3.2.1.intellisense.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
          
        });
    </script>
    }